name: Tests

on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pip install pipenv
      - name: Install development dependencies
        run: pipenv install --dev
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /src/data
          key: ${{ runner.os }}-${{ hashFiles('/src/main.py') }}
      - name: Run tests
        run: pipenv run test